### ISSUE TITLE
take profit and stop loss 

### ISSUE THREAD

**Issue by Sulaimanmohsen** [fabston/TradingView-Webhook-Bot#100]
## Summary
sir i want to add take profit and stop losee targets 

simply its to * the close price by presenting % pleas can you help 

like this 

TLMUSDT  -   Buy          
              
Exchange :   Binance,   FTX,   ByBit,   Kucoin,   BitMEX,    Bitterx,    Huobi.pro
              
Entry Price:    0.02632  -  0.02653056      
              
TP1:    0.0268464  (  1%  )    
TP2:    0.0273728  (  2%  )    
TP3:    0.0278992  (  3%  )    
TP4:    0.0284256  (  4%  )    
TP5:    0.028952  (  5%  )    
              
SL:    0.0255304  (  -3%  )

**Comment by fabston** [comment]
You would have to either include the TP price levels in your pine script or you would have to add extra code to the python script.

This isn’t something I am planning to add tho.
