### ISSUE TITLE
No module named 'tweepy'

### ISSUE THREAD

**Issue by t0000** [fabston/TradingView-Webhook-Bot#111]
## Describe the bug
(TradingView-Webhook-Bot) root@vps-63 ~/TradingView-Webhook-Bot # python main.py
Traceback (most recent call last):
  File "/root/TradingView-Webhook-Bot/main.py", line 13, in <module>
    from handler import *
  File "/root/TradingView-Webhook-Bot/handler.py", line 11, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
(TradingView-Webhook-Bot) root@vps-63 ~/TradingView-Webhook-Bot # pip3 install tweepy
Requirement already satisfied: tweepy in ./lib/python3.9/site-packages (3.10.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in ./lib/python3.9/site-packages (from tweepy) (1.3.0)
Requirement already satisfied: requests[socks]>=2.11.1 in ./lib/python3.9/site-packages (from tweepy) (2.25.1)
Requirement already satisfied: six>=1.10.0 in ./lib/python3.9/site-packages (from tweepy) (1.16.0)
Requirement already satisfied: oauthlib>=3.0.0 in ./lib/python3.9/site-packages (from requests-oauthlib>=0.7.0->tweepy) (3.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./lib/python3.9/site-packages (from requests[socks]>=2.11.1->tweepy) (1.26.5)
Requirement already satisfied: certifi>=2017.4.17 in ./lib/python3.9/site-packages (from requests[socks]>=2.11.1->tweepy) (2021.5.30)
Requirement already satisfied: chardet<5,>=3.0.2 in ./lib/python3.9/site-packages (from requests[socks]>=2.11.1->tweepy) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in ./lib/python3.9/site-packages (from requests[socks]>=2.11.1->tweepy) (2.10)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in ./lib/python3.9/site-packages (from requests[socks]>=2.11.1->tweepy) (1.7.1)
(TradingView-Webhook-Bot) root@vps-63 ~/TradingView-Webhook-Bot #

### Environment
 - OS: debian

**Comment by fabston** [comment]
Seems like you did not install tweety. Be sure to install required packages.

**Comment by erikreimann** [comment]
Hey guys, on Ubuntu 24.04 I got an error message when installing the requirements. I then got the error described above. After installing the build-essential package and updating pip the requirements installation went fine and main.py is starting without any error.

apt-get install build-essential python3-dev

pip install --upgrade pip
