### ISSUE TITLE
webhook on local machine

### ISSUE THREAD

**Issue by mramitdas** [fabston/TradingView-Webhook-Bot#40]
Hi there,

i am strugelling while trying to get the webhook on my local machine.

what should i put in webhook url (Trading view Website)

![Screenshot (49)](https://user-images.githubusercontent.com/51442266/112800174-ef53cd80-908c-11eb-9c8c-5a6f3047f510.png)

which ip you are talking about ( ipv4 (192.168..) or internet ip (45. **. **. **) )

Thanks in advance☺

**Comment by fabston** [comment]
Replied in #39.
