### ISSUE TITLE
warning:waitress message

### ISSUE THREAD

**Issue by JaapS6** [fabston/TradingView-Webhook-Bot#41]
I am running the bot on a windows 10 VPS and have just found this:

WARNING:waitress.queue:Task queue depth is 1
WARNING:waitress.queue:Task queue depth is 2
WARNING:waitress.queue:Task queue depth is 3

I haven't noticed it before and there haven't been any alerts in the TG channel for a few days so I assume something is wrong.

Thanks

**Comment by fabston** [comment]
Hi,

Try removing waitress in [main.py](https://github.com/fabston/TradingView-Webhook-Bot/blob/cb431288d7f0ddba77a1c4daa2eedf34aa5aa93a/main.py#L41-#L44) altogether:

```py
if __name__ == '__main__':
    app.run()
```

**Comment by JaapS6** [comment]
Thanks for the reply. I tried that but it didn't seem to work. 

This is how my main.py looks. I removed all of the section of code at the bottom including the port stuff and replaced with your suggestion but it didn't work. 

I should add that I'm using an older version of the bot from late december.

![image](https://user-images.githubusercontent.com/75375504/113050561-e2260400-919c-11eb-9d64-a9a931d513a5.png)

**Comment by fabston** [comment]
It might be a good idea to update the bot then. But be sure to adjust alerts to json strings as explained in the readme. 

In the screenshot I don't see that you've removed waitress though.

**Comment by JaapS6** [comment]
No, that is the original config. As I said I tried removing that last block of code and replacing with what you suggested, but no luck. Is that what you meant - replace all of that last block of code? 

Sure yes it might be a good idea to update it, but as it took a long time to set up in the first place I'd rather not change anything if I don't have to.

**Comment by JaapS6** [comment]
![image](https://user-images.githubusercontent.com/75375504/113052922-9e80c980-919f-11eb-8b36-085f6e8959b4.png)
if I remove the last block of code and replace with your suggestion I am getting a flask error message

**Comment by fabston** [comment]
I'd then just recommend to keep your old setup and setup another folder with the current version. That way you could easily fall back in case its not working. 

I'll take a look at the correct flask code tomorrow then.

**Comment by JaapS6** [comment]
![image](https://user-images.githubusercontent.com/75375504/113053159-e0117480-919f-11eb-9f12-8020a83a63fe.png)
 like this. So maybe I am doing something wrong.

I restarted with the original code and it's working.

**Comment by fabston** [comment]
You are not running it in a virtual environment?

**Comment by JaapS6** [comment]
On a VPS. However, that previous screencap was probably me mistyping the start command, so please ignore that.

This is the error I get using the adjusted code:
![image](https://user-images.githubusercontent.com/75375504/113054140-fa981d80-91a0-11eb-9bab-4e91c13e2497.png)

**Comment by JaapS6** [comment]
I say error - it's not an error I suppose but it's not working

**Comment by JaapS6** [comment]
But, as I also said, restarting it with the original code works.

**Comment by fabston** [comment]
Instead of:
```py
if __name__ == '__main__':
    app.run()
```

Use:
```py
if __name__ == '__main__':
      app.run(host='0.0.0.0', port=80)
```

**Comment by fabston** [comment]
Awesome!
