### ISSUE TITLE
Twitter Notification also posting secret key

### ISSUE THREAD

**Issue by kaniick** [fabston/TradingView-Webhook-Bot#47]
The twitter bot notifications also post the secret key with the message. Is there a way to not tweet the secret key?

**Comment by fabston** [comment]
Really? That's odd, should not be the case. Will look into that tomorrow.

**Comment by kaniick** [comment]
Yes, I thought it was odd as well. If you need anything from me to help correct the problem please let me know.

**Comment by kaniick** [comment]
![image](https://user-images.githubusercontent.com/11809428/116156780-c8df7d00-a6a0-11eb-9e7f-e25ece8b6a6c.png)

**Comment by fabston** [comment]
I just pushed a new commit that should fix the issue. Please update your bot and let me know if that solved the problem. Thank you.

**Comment by fabston** [comment]
I actually have to remove the markdown rules on Tweets. Will send another fix shortly.

**Comment by fabston** [comment]
Ok, the last commit now also removes markdown rules from Tweets, since Twitter is not supporting it.
