### ISSUE TITLE
Webhook status code 404

### ISSUE THREAD

**Issue by Yoken0S** [fabston/TradingView-Webhook-Bot#48]
Hi,

In log I can see that I receive alert but there is an error message: 
`
2021-04-29 16:23:18 Alert Received & Sent!
ERROR:discord_webhook.webhook:[1/1] Webhook status code 404: {"message": "404: Not Found", "code": 0}
`
My Trading view alert message is:
`
{
 "key": "mysecretkey"
 "msg": Long #{{ticker}} at {{close}}"
}
`

I'm using only Discord for now, sec_key is the same here my discord setting : 
`
#Discord Settings
send_discord_alerts = True
discord_webhook = 'https://discord.com/api/webhooks/835172144408821811/verytoolongcode
`

I don't think it is a link with my configuration but for informations:
I'm on apache2 and use a reverse proxy on a http subdomain to sent it to the flask server host on port 8088.

**Comment by fabston** [comment]
Hi,

The json string is looking wrong. You forgot a comma between `key` and `msg` as well as `"` in front of your msg content. Please try:

```json
{"key": "mysecretkey", "msg": "Long #{{ticker}} at {{close}}"}
```

**Comment by Yoken0S** [comment]
@fabston Hi it is an error in my github message but the comme is present on my TV Alert ;)

**Comment by fabston** [comment]
Please share your the syntax that you have used in the TradingView alerts box. Because in the one you shared here you also missed a `"` which will break the code.

**Comment by Yoken0S** [comment]
**
![image](https://user-images.githubusercontent.com/67964703/116673522-caac8780-a9a3-11eb-8fd7-928db8287083.png)
**
Image to avoid Github breaks anything

**Comment by Yoken0S** [comment]
**
![image](https://user-images.githubusercontent.com/67964703/116673659-f6c80880-a9a3-11eb-8d48-ab1c741363cb.png)
**
Image to avoid github breaks anything

**Comment by fabston** [comment]
Ok. 

Now lets take a closer look at your `config.py`. From what I can see on your initial post you also included `https://discord.com/api/webhooks/` in `discord_webhook`. Is that correct?

If so, please remove that part entirely. A valid input would look like:
`discord_webhook = '803597983144476732/1zUtzAC1akp8Z2pWahnmmgM4vN4ZdvtWbJvL20QrG9AolgWzMBrDhritqKdS3yNbIceE'`

**Comment by Yoken0S** [comment]
@fabston  Yes it was that ^^"
Thank you boss !

**Comment by fabston** [comment]
Your welcome!
