### ISSUE TITLE
"embeds": ["0"]

### ISSUE THREAD

**Issue by Yoken0S** [fabston/TradingView-Webhook-Bot#51]
I got an error message on my server with my TV alert.

Here the error :
`ERROR:discord_webhook.webhook:[1/1] Webhook status code 400: {"embeds": ["0"]}`

Here the message: 
`
{
 "key": "mysecretkeythatisthesameassecond",
 "discord": "8351721444088.....6sO",
 "msg": "---------------------------------------- \n\n Attention Trade court et à prendre au moment de l alerte! \n\n Alerte: {{ticker}} - Achat - type 5Min \n\n {{time}} heure UTC \n\n Plateforme {{exchange}}. \n\n Achat {{ticker}} au prix de {{close}}. \n\n Plus votre prix d entrée est bas au moment de l alerte plus vos risques de profit en sortie seront bas. \n\n Pour plus de sécurité sur votre prise de trade: \n\n Vérifier que votre moyenne mobile 100 soit haut dessus de votre bougie de clôture en 5Min. \n\n Pour votre clôture: \n\n Compter entre 0.35% risque faible, 0.5% risque moyen et 0.75% risque plus élevé. \n\n ----------------------------------------"
}
`

Here my config file:
`
send_discord_alerts = True
discord_webhook = '8351721444088....6sO' 
`

**Comment by Yoken0S** [comment]
I tried by re moving all accents, point . , double points : , apasthrophe ', special aposthrophe ... there is just - and alphanumeric and backslash n still same error.

`
{
 "key": "TXQJiB6tij",
 "discord": "835172144408821811/mD9PuGv-Jfw_KS1kJ1CtHoRFgV8X3yfwlQJvpfLyWWdPRW29AZRjFq_gasHCHQ1nF6sO",
 "msg": "---------------------------------------- \n\n Attention Trade court et a prendre au moment de l alerte \n\n Alerte `{{ticker}}`  Achat  type 5Min \n\n `{{time}}` heure UTC \n\n Plateforme `{{exchange}}` \n\n Achat `{{ticker}}` au prix de `{{close}}` \n\n Plus votre prix d entree est bas au moment de l alerte plus vos risques de profit en sortie seront bas \n\n Pour plus de securite sur votre prise de trade \n\n Verifier que votre moyenne mobile 100 soit haut dessus de votre bougie de cloture en 5Min \n\n Pour votre cloture \n\n Compter entre 035 pourcent risque faible 05 pourcent risque moyen et 075 pourcent risque plus eleve \n\n"
}
`

**Comment by fabston** [comment]
The bot is using the `title` field in the Discord embed. And the char limit for that is **256**.

You might want to change that to `description` in [handle.py](https://github.com/fabston/TradingView-Webhook-Bot/blob/82d62ffceecbc0d832a92e253b821167c3df86ac/handler.py#L33). That would allow up to **2048** chars.

**Comment by Yoken0S** [comment]
Damn it I should find it xD

Thank you I chanegd the handler.py and works like charm now 👍

**Comment by fabston** [comment]
No worries at all. Glad it fixed it!
