### ISSUE TITLE
error on Raspberry Pi 3

### ISSUE THREAD

**Issue by philobbe** [fabston/TradingView-Webhook-Bot#52]
## Description

error message on launch

### Steps to reproduce

- follow install instructions
- launch `python main.py` 

### Expected result

- start

### Actual result

`python main.py
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from handler import *
  File "/home/pi/botdiscord/TradingView-Webhook-Bot/handler.py", line 8, in <module>
    from telegram import Bot
ImportError: No module named telegram
`
### Environment

- Raspberry Pi 3

**Comment by fabston** [comment]
Hi,

did you run `pip install -r requirements` inside your virtual environment?

**Comment by philobbe** [comment]
yes I followed your commands. I tried sevral times.

**Comment by fabston** [comment]
Please run `pip list` and show me the output.

**Comment by philobbe** [comment]
`pi@raspberrypi:~/botdiscord/TradingView-Webhook-Bot $ pip list
Package           Version    
----------------- -----------
arandr            0.1.9      
asn1crypto        0.24.0     
automationhat     0.2.0      
blinker           1.4        
blinkt            0.1.2      
buttonshim        0.0.2      
Cap1xxx           0.1.3      
certifi           2018.8.24  
chardet           3.0.4      
Click             7.0        
colorama          0.3.7      
colorzero         1.1        
configparser      3.5.0b2    
cookies           2.2.1      
cryptography      2.6.1      
drumhat           0.1.0      
entrypoints       0.3        
enum34            1.1.6      
envirophat        1.0.0      
ExplorerHAT       0.4.2      
Flask             1.0.2      
fourletterphat    0.1.0      
funcsigs          1.0.2      
gpiozero          1.5.1      
gyp               0.1        
idna              2.6        
ipaddress         1.0.17     
itsdangerous      0.24       
Jinja2            2.10       
keyring           17.1.1     
keyrings.alt      3.1.1      
MarkupSafe        1.1.0      
mcpi              0.1.1      
microdotphat      0.2.1      
mock              2.0.0      
mote              0.0.4      
motephat          0.0.3      
numpy             1.16.2     
oauthlib          2.1.0      
olefile           0.46       
pantilthat        0.0.7      
pbr               4.2.0      
phatbeat          0.1.1      
pianohat          0.1.0      
picamera          1.13       
picraft           1.0        
piglow            1.2.5      
pigpio            1.78       
Pillow            5.4.1      
pip               18.1       
pycairo           1.16.2     
pycrypto          2.6.1      
pyflakes          2.0.0      
pygame            1.9.4.post1
PyGObject         3.30.4     
pyinotify         0.9.6      
PyJWT             1.7.0      
pyOpenSSL         19.0.0     
pyserial          3.4        
pyxdg             0.25       
rainbowhat        0.1.0      
requests          2.21.0     
requests-oauthlib 1.0.0      
responses         0.9.0      
RPi.GPIO          0.7.0      
RTIMULib          7.2.1      
scrollphat        0.0.7      
scrollphathd      1.2.1      
SecretStorage     2.3.1      
sense-emu         1.1        
sense-hat         2.2.0      
setuptools        40.8.0     
simplejson        3.16.0     
six               1.12.0     
skywriter         0.0.7      
sn3218            1.2.7      
spidev            3.4        
touchphat         0.0.1      
twython           3.7.0      
unicornhathd      0.0.4      
urllib3           1.24.1     
Werkzeug          0.14.1     
wheel             0.32.3 `

**Comment by fabston** [comment]
I don’t see the telegram package in it. That’s why your getting the error you mentioned.

**Comment by philobbe** [comment]
yes it seems the package is not here. How can we solve that ?

**Comment by philobbe** [comment]
maybe the package is not the some for raspberry ?

**Comment by fabston** [comment]
Are you using a virtual environment?

**Comment by philobbe** [comment]
No. I just use a raspberry with fresh install and just followed your installation notice

**Comment by fabston** [comment]
Please take a look [here](https://github.com/fabston/TradingView-Webhook-Bot#installation) step 2.

**Comment by philobbe** [comment]
Oh yes I followed this.
I did all the steps exactly like it is explained.

**Comment by fabston** [comment]
In your Print statement it looks not like you activated it. However try: `pip install -r requirements.txt --no-cache-dir`

**Comment by philobbe** [comment]
do I have to do the entire processus by the start and in step 4 type this command

**Comment by fabston** [comment]
Run the command I mentioned inside of your virtual environment.

**Comment by philobbe** [comment]
`(TradingView-Webhook-Bot) pi@raspberrypi:~/botdiscord/TradingView-Webhook-Bot $ pip install -r requirements.txt --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting flask (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/f2/28/2a03252dfb9ebf377f40fba6a7841b47083260bf8bd8e737b0c6952df83f/Flask-1.1.2-py2.py3-none-any.whl (94kB)
    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 102kB 348kB/s 
Collecting waitress (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/a8/cf/a9e9590023684dbf4e7861e261b0cfd6498a62396c748e661577ca720a29/waitress-2.0.0-py3-none-any.whl (56kB)
    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 61kB 823kB/s 
Collecting python-telegram-bot (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/e4/44/1726f407387a7332a08b4e95211380b3bda185cedbe73d1058010136e695/python_telegram_bot-13.5-py3-none-any.whl (455kB)
    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 460kB 1.0MB/s 
Collecting discord-webhook (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/16/ba/1db1ba5a0f3c4883099d5b818ba713e00be4abb70eab6979e96e308e3b98/discord_webhook-0.13.0-py3-none-any.whl
Collecting slack-webhook (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/7c/5f/51006761d70df4f13df94d577a826f5a8d28f3097db33eceea529162fdb2/slack_webhook-1.0.6-py3-none-any.whl
Collecting tweepy (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/67/c3/6bed87f3b1e5ed2f34bd58bf7978e308c86e255193916be76e5a5ce5dfca/tweepy-3.10.0-py2.py3-none-any.whl
Collecting Werkzeug>=0.15 (from flask->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/cc/94/5f7079a0e00bd6863ef8f1da638721e9da21e5bacee597595b318f71d62e/Werkzeug-1.0.1-py2.py3-none-any.whl (298kB)
    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 307kB 2.1MB/s 
Collecting itsdangerous>=0.24 (from flask->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl
Collecting click>=5.1 (from flask->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl (82kB)
    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 92kB 868kB/s 
Collecting Jinja2>=2.10.1 (from flask->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/7e/c2/1eece8c95ddbc9b1aeb64f5783a9e07a286de42191b7204d67b7496ddf35/Jinja2-2.11.3-py2.py3-none-any.whl (125kB)
    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 133kB 125kB/s 
Collecting pytz>=2018.6 (from python-telegram-bot->-r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/70/94/784178ca5dd892a98f113cdd923372024dc04b8d40abe77ca76b5fb90ca6/pytz-2021.1-py2.py3-none-any.whl (510kB)
    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 512kB 590kB/s 
Collecting APScheduler==3.6.3 (from python-telegram-bot->-r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/f3/34/9ef20ed473c4fd2c3df54ef77a27ae3fc7500b16b192add4720cab8b2c09/APScheduler-3.6.3-py2.py3-none-any.whl (58kB)
    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 61kB 852kB/s 
Collecting certifi (from python-telegram-bot->-r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/5e/a0/5f06e1e1d463903cf0c0eebeb751791119ed7a4b3737fdc9a77f1cdfb51f/certifi-2020.12.5-py2.py3-none-any.whl (147kB)
    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 153kB 674kB/s 
Collecting tornado>=5.1 (from python-telegram-bot->-r requirements.txt (line 3))
  Downloading https://www.piwheels.org/simple/tornado/tornado-6.1-cp37-cp37m-linux_armv7l.whl (428kB)
    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 430kB 5.4MB/s 
Collecting requests>=2.19.1 (from discord-webhook->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/29/c1/24814557f1d22c56d50280771a17307e6bf87b70727d975fd6b2ce6b014a/requests-2.25.1-py2.py3-none-any.whl (61kB)
    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 61kB 807kB/s 
Collecting requests-oauthlib>=0.7.0 (from tweepy->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/a3/12/b92740d845ab62ea4edf04d2f4164d82532b5a0b03836d4d4e71c6f3d379/requests_oauthlib-1.3.0-py2.py3-none-any.whl
Collecting six>=1.10.0 (from tweepy->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.10.1->flask->-r requirements.txt (line 1))
  Downloading https://www.piwheels.org/simple/markupsafe/MarkupSafe-1.1.1-cp37-cp37m-linux_armv7l.whl
Requirement already satisfied: setuptools>=0.7 in ./lib/python3.7/site-packages (from APScheduler==3.6.3->python-telegram-bot->-r requirements.txt (line 3)) (40.8.0)
Collecting tzlocal>=1.2 (from APScheduler==3.6.3->python-telegram-bot->-r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/5d/94/d47b0fd5988e6b7059de05720a646a2930920fff247a826f61674d436ba4/tzlocal-2.1-py2.py3-none-any.whl
Collecting urllib3<1.27,>=1.21.1 (from requests>=2.19.1->discord-webhook->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/09/c6/d3e3abe5b4f4f16cf0dfc9240ab7ce10c2baa0e268989a4e3ec19e90c84e/urllib3-1.26.4-py2.py3-none-any.whl (153kB)
    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 153kB 707kB/s 
Collecting chardet<5,>=3.0.2 (from requests>=2.19.1->discord-webhook->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/19/c7/fa589626997dd07bd87d9269342ccb74b1720384a4d739a1872bd84fbe68/chardet-4.0.0-py2.py3-none-any.whl (178kB)
    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 184kB 674kB/s 
Collecting idna<3,>=2.5 (from requests>=2.19.1->discord-webhook->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl (58kB)
    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 61kB 892kB/s 
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->tweepy->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/05/57/ce2e7a8fa7c0afb54a0581b14a65b56e62b5759dbc98e80627142b8a3704/oauthlib-3.1.0-py2.py3-none-any.whl (147kB)
    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 153kB 779kB/s 
Installing collected packages: Werkzeug, itsdangerous, click, MarkupSafe, Jinja2, flask, waitress, pytz, six, tzlocal, APScheduler, certifi, tornado, python-telegram-bot, urllib3, chardet, idna, requests, discord-webhook, slack-webhook, oauthlib, requests-oauthlib, tweepy
Successfully installed APScheduler-3.6.3 Jinja2-2.11.3 MarkupSafe-1.1.1 Werkzeug-1.0.1 certifi-2020.12.5 chardet-4.0.0 click-7.1.2 discord-webhook-0.13.0 flask-1.1.2 idna-2.10 itsdangerous-1.1.0 oauthlib-3.1.0 python-telegram-bot-13.5 pytz-2021.1 requests-2.25.1 requests-oauthlib-1.3.0 six-1.16.0 slack-webhook-1.0.6 tornado-6.1 tweepy-3.10.0 tzlocal-2.1 urllib3-1.26.4 waitress-2.0.0
(TradingView-Webhook-Bot) pi@raspberrypi:~/botdiscord/TradingView-Webhook-Bot $ `

**Comment by philobbe** [comment]
`pi@raspberrypi:~/botdiscord/TradingView-Webhook-Bot $ python main.py
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from handler import *
  File "/home/pi/botdiscord/TradingView-Webhook-Bot/handler.py", line 8, in <module>
    from telegram import Bot
ImportError: No module named telegram
pi@raspberrypi:~/botdiscord/TradingView-Webhook-Bot $ 
`

**Comment by philobbe** [comment]
how can I resolve that ?

**Comment by fabston** [comment]
I can’t seem to further assist you without access to your server. I’d recommend you to take a look at [WebhookAlerts.com](https://webhookalerts.com).
