### ISSUE TITLE
telegram broken

### ISSUE THREAD

**Issue by alazare619** [fabston/TradingView-Webhook-Bot#53]
Brand new install
Steps followed exact as readme
Appears the telegram current library is no longer compatiable i can send a curl to the link

https://api.telegram.org/bot1880082849:AAEA3upXKroG6PyxToxMWS7eGVFnlaHuH5I/sendMessage?chat_id=-1000234234&text=booooo

it appears in the channel however the bot does not work. maybe revert back? or lock it to a certain python-telegram-bot version

**Comment by fabston** [comment]
Works just fine for me. Your chat id looks wrong though, might wanna double check that one.
