### ISSUE TITLE
Idea:

### ISSUE THREAD

**Issue by theoneaykay** [fabston/TradingView-Webhook-Bot#54]
## Summary

Letting users ask for trading view ideas in like a group chat for example, by using commands, like in this telegram group they use /ideas and the coin name and it shows different latest TA that where posted on that specific coin on trading view.

### Basic example

Here is a link to the channel I saw it in: https://t.me/TheMoonGroup

Here is directl link the the bot channel: https://t.me/Whale_Tracker

its on telegram

### Motivation

That bot has many more features u can explore but that will make the group chat on discord more lively and more people can discuss and talk about different scenarios or trade opportunities.

**Comment by fabston** [comment]
Hi @theoneaykay,

I appreciate your suggestion. As it looks to me that would be more of a new project. It won't really work / fit with this project.
