### ISSUE TITLE
sometimes work fine some not..!

### ISSUE THREAD

**Issue by jpadron1983** [fabston/TradingView-Webhook-Bot#62]
**Describe the bug:**

|TV-Webho | 2021-06-21 17:10:31 Alert Received & Sent!
0|TV-Webho | [X] Telegram Error:
0|TV-Webho | > Invalid server response

**Steps to reproduce:**
Steps to reproduce the behavior.

**Expected behavior:**

**Environment:**
 - OS: [e.g. Arch Linux]
 - Other details that you think may affect.

**Additional context:**

**Comment by jpadron1983** [comment]
sorry..! was msg format

**Comment by fabston** [comment]
Great. Glad you sorted it out.
