### ISSUE TITLE
Add a delay between sending alerts

### ISSUE THREAD

**Issue by babovand** [fabston/TradingView-Webhook-Bot#66]
## Summary
Add a delay between sending alerts

### Basic example
If you could make this happen, make it an option in main config and also another parameter to control the delay for which the alert is sent in milliseconds after the previous alert was sent.

### Motivation
I have many of my alerts (over 60) set at once per bar on tradingview on daily charts. That means every day at market open i get multiple alerts that I want to have, but some of them don't reach telegram because of these errors

```
Jun 25 15:30:08 web pipenv[659]: WARNING:waitress.queue:Task queue depth is 1
Jun 25 15:30:09 web pipenv[659]: WARNING:waitress.queue:Task queue depth is 2
Jun 25 15:30:11 web pipenv[659]: WARNING:waitress.queue:Task queue depth is 3
Jun 25 15:30:11 web pipenv[659]: [X] Telegram Error:
Jun 25 15:30:11 web pipenv[659]: > Timed out

```
So Im guessing both flask/waitress and telegram times-out because of spam
One solution I've found is to host another webhook or make another bot but thats tedious and makes it hard to manage my 300+ alerts plus friends that are using the same webhook

Thank you for reading this, and thank you again for this awesome tradingview webkook for telegram

**Comment by fabston** [comment]
Hi,

It would be a better idea to wrap it around `try` and `except`. Hope that helps.

**Comment by fabston** [comment]
Due to inactive I am closing this issue.
