### ISSUE TITLE
reached Connection Limits

### ISSUE THREAD

**Issue by llerch** [fabston/TradingView-Webhook-Bot#67]
Hi Mate

I get the following Errors. What it the Problem?

Kind regards,
Luca

<img width="728" alt="image" src="https://user-images.githubusercontent.com/45877247/126047590-b1a9a4fb-2d96-46c5-94a2-c1e39d52a327.png">

**Comment by fabston** [comment]
Hi,

I am not too sure. I never ran into that error. Might want to remove `waitress` and see if that helps.

**Comment by fabston** [comment]
Due to inactivity I am closing this issue now.
