### ISSUE TITLE
404 Error on simple message

### ISSUE THREAD

**Issue by riodda** [fabston/TradingView-Webhook-Bot#68]
## Describe the bug
I receive a 404 Message on console at webhook receive

### Steps to reproduce
Setup a basic TV alert

{
 "key": <MYKEY>,
"msg": "PIPPO"
}

Console output is 

ERROR:discord_webhook.webhook:[1/1] Webhook status code 404: {"message": "404: Not Found", "code": 0}

If the discord webhook is added to the message the message is forwarded correctly to discord, is the webhook is specifyed in config.py is ignored and the system returns the 404 error.

### Expected behavior
The message is forwarded to discord

### Environment
 - OS: Ubuntu 20.04 VPS
 - Fresh installation

**Comment by fabston** [comment]
Hi, 

Your JSON string looks incomplete. Please take a look at the readme in which I explained it.
