### ISSUE TITLE
405 Method not allower

### ISSUE THREAD

**Issue by riodda** [fabston/TradingView-Webhook-Bot#69]
## Describe the bug
I created a test channel for the tv alert on my discord sever, created the webhook and i was receiving the alerts properly.
Then i created a webhook on an existing channel and i have the error

ERROR:discord_webhook.webhook:[1/1] Webhook status code 405: {"message": "405: Method Not Allowed", "code": 0}

### Steps to reproduce
Steps to reproduce the behavior.

### Environment
- ubuntu 20.04 VPS

**Comment by fabston** [comment]
Hi,

I need more information. A debug log would be helpful.

**Comment by fabston** [comment]
Due to inactivity I am closing this issue now.

**Comment by riodda** [comment]
> Hi,
> 
> I need more information. A debug log would be helpful.

How can I create a debug log ? Sorry for the nob question.

**Comment by riodda** [comment]
Hi, can you let me know how to produce the log ?
