### ISSUE TITLE
> 'NoneType' object is not subscriptable 

### ISSUE THREAD

**Issue by camiloavil** [fabston/TradingView-Webhook-Bot#92]
i get this when the alert is made > 'NoneType' object is not subscriptable

**Comment by fabston** [comment]
Hi there,

Are you able to provide more logs, this is not saying much.

**Comment by DenisKaizer** [comment]
Hi I have the same issue
<img width="652" alt="image" src="https://user-images.githubusercontent.com/22869112/173391270-b71935f3-ae8f-4551-8bed-b69e33dd6e3c.png">

**Comment by fabston** [comment]
What syntax are you using?

**Comment by DenisKaizer** [comment]
EURUSD Less Than 1.06304

**Comment by krypto-san** [comment]
I got that error too as I was trying to send an alert with an indicator and the indicator did not have the option to type the massage. 
![tv1](https://user-images.githubusercontent.com/84674045/174410914-12b39310-e362-482c-828e-e87286769ecc.png)

**Comment by krypto-san** [comment]
> EURUSD Less Than 1.06304

the syntax below would work for you. you also need to add your telegram channel id to syntax.


{
 "key": "",
 "telegram": "",
 "discord": "",
 "slack": "T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX",
 "msg": "EURUSD Less Than 1.06304"
}
